---
kind: pipeline
type: docker
name: restful

platform:
  os: linux
  arch: arm

steps:
- name: publish docker container
  image: plugins/docker
  settings:
    custom_dns: 172.16.10.39
    repo: docker-registry.rumpfhuber.icu/crumpfhuber/htlw4-spaceshooter
    registry: docker-registry.rumpfhuber.icu
    tags: latest
    dockerfile: ./Dockerfile
