---
kind: pipeline
type: docker
name: restful

steps:
- name: publish docker container
  image: plugins/docker
  settings:
    repo: docker-registry.rumpfhuber.icu/crumpfhuber/htlw4-spaceshooter
    registry: 172.16.10.30
    tags: latest
    dockerfile: ./Dockerfile
